name: JD Feature Image
slug: jd-feature-image
groups: JoomDev
form:
  general:
    - name: image
      type: file-manager
      label: Image Url
      help: Upload your desired image, or type in the URL to the image you would like to display.

    - name: alt_text
      type: text
      depends:
        image: '*'

    - name: title_text
      type: text 
      depends:
        image: '*'

    - name: content
      type: editor
      value: Lorem ipsum dolor sit amet timeam deleniti mnesarchum ex sed alii hinc dolores ad cum. Urbanitas similique ex nam paulo temporibus ea vis id odio adhuc nostrum eos.
  styles:
    - name: content_bgcolor
      type: color
      label: Content Background

    - name: border
      type: switch
      label: Use Border

    - name: border_width
      type: slider
      label: Border Width
      value: 2
      suffix: px
      depends:
        border: true

    - name: border_radius
      type: slider
      label: Border Radius
      value: 3
      suffix: px
      depends:
        border: true

    - name: border_style
      type: select
      value: solid
      depends:
        border: true
      options:
        solid: Solid
        dotted: Dotted
        dashed: Dashed
        double: Double
        groove: Groove
        ridge: Ridge
        inset: Inset
        outset: Outset

    - name: border_color
      type: color
      label: Border Color
      depends:
        border: true

    - name: border_hover_color
      type: color
      label: Border Hover Color
      depends:
        border: true